### ISSUE TITLE
O365 retriever does not handle unicode correctly

### ISSUE THREAD

**Issue by metamoof** [CrowdStrike/Forensics#10]
```C:\Dev\Forensics\O365-Outlook-Activities>python retriever.py --user user@contoso.com --start 2018-06-01T00:00:00Z --output user.csv
Retrieving activities................Traceback (most recent call last):
  File "retriever.py", line 109, in <module>
    writer.writerow(vars(activity))
  File "C:\Python\Python36-32\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 732-733: character maps to <undefined>
```

I've fixed this by adding `encoding='utf8'` to line 95, but I'm not sure that this isn't better handled as a command-line switch. Also, as you seem to be python 2 compatible, it needs handling for that too.

**Comment by jonathanitzhaky** [comment]
Thank you for reporting this. Will add `encoding='utf-8-sig'` (to add UTF-8 BOM) and simply drop 2.7 support.

**Comment by robsmallridge** [comment]
Think your fix has added a new bug. Was working fine for me yesterday. 

Now getting: 

File "retriever.py", line 99
    print('Retrieving activities', end='')

**Comment by robsmallridge** [comment]
I left a comment on this which have deleted - please ignore. Issue was because I was using python 2.7 not Python3. Thanks for the tool release! great work

**Comment by jonathanitzhaky** [comment]
Thanks. Changes were committed. Closing issue.
