### ISSUE TITLE
O365-Outlook-Activities Error: AppId is not allowed

### ISSUE THREAD

**Issue by tyrells** [CrowdStrike/Forensics#11]
Hello,

Thank you for this great tool. I am trying to run it to collect activity logs for a user but I get the following error:

HTTP 403: AppId: "32613fc5-e7ac-4894-ac94-fbc39c9f3e4a" is not allowed.

This AppId seems to be associated with the Outlook Dev Center - OAuth Sandbox. I have granted my user the required permissions using the Add-MailboxPermission command.

**Comment by cs-jonathan** [comment]
Unfortunately, access to this undocumented API has been suspended by Microsoft.
