### ISSUE TITLE
O365-Outlook-Activities No Longer Functional

### ISSUE THREAD

**Issue by kurobeats** [CrowdStrike/Forensics#14]
It appears as though all functionality from the O365-Outlook-Activities utility has been removed by Microsoft.

Is this tool still being developed or is it dead?

**Comment by LukeHealy** [comment]
I can confirm that this script is not entirely useless as Microsoft have revokes access to the API it uses. You will just get 403's.

**Comment by kurobeats** [comment]
THANKS FOR ANSWERING MY QUESTION PRIOR TO CLOSING JONATHAN

**Comment by cs-jonathan** [comment]
@LukeHealy's response was accurate. Additionally, the README has been updated to reflect the fact that Microsoft has restricted access to the API. Have a nice day.
