### ISSUE TITLE
HTTP 403: AppId: "32613fc5-e7ac-4894-ac94-fbc39c9f3e4a" is not allowed.

### ISSUE THREAD

**Issue by zoddd** [CrowdStrike/Forensics#16]
I was able to run this back in June without issue, but now I am getting this error when running:
python retriever.py --user victim@domain.com --output activities.csv --token <token generated from oauthplay.azurewebsites.net>

toke was generated from account that has fullaccess permissions to victim mailbox.

**Comment by cs-jonathan** [comment]
Unfortunately, Microsoft has revoked public access to the API. The tool will no longer function. Thanks for commenting.
