### ISSUE TITLE
Add support for CreateRemoteThread ID 8

### ISSUE THREAD

**Issue by holisticinfosec** [CrowdStrike/Forensics#4]
Greetings. 

Suggest updating line 55 in sysmon_parse.cmd to include ID 8, added to Sysmon on 20 JUL 2015 to identify CreateRemoteThread events.
Suggested change as follows:
tools\logparser\logparser -i:evt -o:csv "Select RecordNumber,TO_UTCTIME(TimeGenerated),EventID,SourceName,ComputerName,SID,Strings from %src% WHERE EventID in ('1';'2';'3';'4';'5';'6';'7';'8')" > Results_%dtstamp%\sysmon_parsed.txt

Cheers.

**Comment by mattchurchill** [comment]
Updated. Thanks, Russ!
